### ISSUE TITLE
Planos para o CGI

### ISSUE THREAD

**Issue by rodrigo-br** [rodrigo-br/Webserv_42#45]
Ao clicar no botão, executar o cgi para criar o arquivo temporário.
Fazer a função que faz o setPath para o cgi_temp setar o path para {ROOT}/assets.
Consequentemente, o cgiExecute deve criar o arquivo temporário nessa pasta.

Requisição esperada : 
1ª - cgi-bin/
2ª - cgi-bin/index.py (antes do cgi execute)
2.1ª - assets/cgi_temp (após o cgi execute)

verificar se o request_validator está retornando true.

**Comment by leaozim** [comment]
feito
